"""Surge 配置文件生成器 - 支持中英文分组名"""

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models import (
    ProxyNode, RegionGroup, ServiceGroup,
    ConfigProfile, RuleSource, Subscription,
    CustomRule, HostMapping,
)
from app.default_config import DEFAULT_GENERAL, DEFAULT_URL_REWRITES, DEFAULT_HEADER_REWRITES, DEFAULT_MITM, locale_translate, CATEGORY_NAMES, COMMENT_NAMES

# 节点名称过滤关键词（与 subscription.py 同步）
FILTER_PATTERN = r"Remain|Expired|官网|如需|套餐|去除|剩余|距离|Reset|重置|流量"


def _quote(name: str) -> str:
    if not name:
        return '""'
    return f'"{name}"' if (" " in name or "]" in name or "[" in name) else name


def _display_name(node: ProxyNode, sub_map: dict) -> str:
    sub_name = sub_map.get(node.subscription_id, "")
    if sub_name:
        return f"({sub_name}) {node.name}"
    return node.name


async def generate_surge_config(db: AsyncSession, profile_id: int | None = None, locale_override: str | None = None) -> str:
    profile = None
    if profile_id:
        result = await db.execute(select(ConfigProfile).where(ConfigProfile.id == profile_id))
        profile = result.scalar_one_or_none()
    if not profile:
        result = await db.execute(select(ConfigProfile).where(ConfigProfile.is_default == True).limit(1))
        profile = result.scalar_one_or_none()

    locale = locale_override or (profile.locale if profile else "zh")

    def t(name: str) -> str:
        return locale_translate(name, locale)

    def tc(key: str) -> str:
        """翻译分类名：zh 用中文名，en 保留英文原名"""
        if locale == "zh" or not locale:
            return CATEGORY_NAMES.get(key, key)
        upper_keys = {"ai", "lan"}
        if key in upper_keys:
            return key.upper()
        return key.replace("_", " ").title()

    def tcomment(key: str) -> str:
        """翻译固定注释"""
        zh, en = COMMENT_NAMES.get(key, (key, key))
        return zh if locale == "zh" or not locale else en

    nodes_result = await db.execute(
        select(ProxyNode).where(ProxyNode.enabled == True).order_by(ProxyNode.name)
    )
    all_nodes = nodes_result.scalars().all()

    regions_result = await db.execute(
        select(RegionGroup).where(RegionGroup.enabled == True).order_by(RegionGroup.sort_order)
    )
    region_groups = regions_result.scalars().all()

    services_result = await db.execute(
        select(ServiceGroup).where(ServiceGroup.enabled == True).order_by(ServiceGroup.sort_order)
    )
    service_groups = services_result.scalars().all()

    rules_result = await db.execute(
        select(RuleSource).where(RuleSource.enabled == True).order_by(RuleSource.sort_order)
    )
    rule_sources = rules_result.scalars().all()

    subs_result = await db.execute(select(Subscription))
    sub_map = {s.id: s.name for s in subs_result.scalars().all()}

    # General
    general = dict(DEFAULT_GENERAL)
    if profile and profile.general:
        general.update(profile.general)

    sections = [
        "# ============================================================",
        "# SurgeConf - Surge Configuration Manager",
        "# This file was generated by SurgeConf, a local configuration",
        "# management tool. Use at your own risk. Ensure your usage",
        "# complies with all applicable laws and regulations.",
        "# ============================================================",
        "",
    ]
    sections.append("[General]")
    for key, value in general.items():
        if isinstance(value, bool):
            sections.append(f"{key} = {'true' if value else 'false'}")
        else:
            sections.append(f"{key} = {value}")
    sections.append("")

    # Proxy
    sections.append("[Proxy]")
    if all_nodes:
        for node in all_nodes:
            display = _display_name(node, sub_map)
            config_line = node.config.replace(node.name, display, 1)
            sections.append(config_line)
    sections.append("")

    # Proxy Group
    sections.append("[Proxy Group]")
    sections.extend(_build_proxy_groups(all_nodes, region_groups, service_groups, t, sub_map))
    sections.append("")

    # Rule
    sections.append("[Rule]")

    # 从新表读取自定义规则
    pre_rules_result = await db.execute(
        select(CustomRule)
        .where(CustomRule.enabled == True, CustomRule.position == "pre")
        .order_by(CustomRule.sort_order)
    )
    pre_rules = pre_rules_result.scalars().all()

    general_rules_result = await db.execute(
        select(CustomRule)
        .where(CustomRule.enabled == True, CustomRule.position == "general")
        .order_by(CustomRule.sort_order)
    )
    general_rules = general_rules_result.scalars().all()

    sections.extend(_build_rules(rule_sources, pre_rules, general_rules, t, tc, tcomment))
    sections.append("")

    # Host
    sections.append("[Host]")
    host_result = await db.execute(
        select(HostMapping)
        .where(HostMapping.enabled == True)
        .order_by(HostMapping.sort_order)
    )
    host_mappings = host_result.scalars().all()
    for m in host_mappings:
        sections.append(f"{m.domain} = {m.target}")
    sections.append("")

    # URL Rewrite
    sections.append("[URL Rewrite]")
    rewrites = profile.url_rewrites if (profile and profile.url_rewrites) else DEFAULT_URL_REWRITES
    for rule in rewrites:
        sections.append(rule)
    sections.append("")

    # Header Rewrite
    sections.append("[Header Rewrite]")
    header_rewrites = profile.header_rewrites if (profile and profile.header_rewrites) else DEFAULT_HEADER_REWRITES
    for rule in header_rewrites:
        sections.append(rule)
    sections.append("")

    # MITM
    sections.append("[MITM]")
    mitm = {**DEFAULT_MITM, **(profile.mitm or {})} if profile else DEFAULT_MITM
    for key, value in mitm.items():
        if isinstance(value, bool):
            sections.append(f"{key} = {'true' if value else 'false'}")
        else:
            sections.append(f"{key} = {value}")
    sections.append("")

    return "\n".join(sections)


def _build_proxy_groups(
    all_nodes: list[ProxyNode],
    region_groups: list[RegionGroup],
    service_groups: list[ServiceGroup],
    t,
    sub_map: dict,
) -> list[str]:
    lines = []

    # 全部节点组
    sub_filter = f"^((?!{FILTER_PATTERN}).)+$"
    lines.append(
        f'{_quote(t("全部节点"))} = select, '
        f'policy-regex-filter={sub_filter}, '
        f'include-all-proxies=1, '
        f'icon-url=https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/05icon/rocket(1).png'
    )
    lines.append("")

    # 筛选活跃地区：至少一个子开关启用
    active_regions = [rg for rg in region_groups if rg.auto_enabled or rg.manual_enabled]
    auto_regions = [rg for rg in active_regions if rg.auto_enabled]
    manual_regions = [rg for rg in active_regions if rg.manual_enabled]

    # ── 自动地区测速组 ──
    for rg in auto_regions:
        icon = f', icon-url={rg.icon_url}' if rg.icon_url else ""
        lines.append(
            f'{_quote(t(rg.name))} = url-test, '
            f'policy-regex-filter={rg.filter_regex}, '
            f'include-other-group={_quote(t("全部节点"))}, '
            f'url=http://cp.cloudflare.com/generate_204, '
            f'interval=300, tolerance=50, timeout=3'
            f'{icon}'
        )

    # 其他地区（自动）— 仅在有自动地区时生成
    if auto_regions:
        all_filters = "|".join(rg.filter_regex for rg in active_regions)
        other_filter = f"^((?!{all_filters}|{FILTER_PATTERN}).)+$"
        lines.append(
            f'{_quote(t("其他"))} = url-test, '
            f'policy-regex-filter={other_filter}, '
            f'include-other-group={_quote(t("全部节点"))}, '
            f'url=http://cp.cloudflare.com/generate_204, '
            f'interval=300, tolerance=50, timeout=3, '
            f'icon-url=https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/EuropeanUnion.png'
        )
    lines.append("")

    # ── 手动地区分组 ──
    manual_region_names = []
    for rg in manual_regions:
        manual_name = f"{rg.name}手动"
        icon = f', icon-url={rg.icon_url}' if rg.icon_url else ""
        lines.append(
            f'{_quote(t(manual_name))} = select, '
            f'policy-regex-filter={rg.filter_regex}, '
            f'include-other-group={_quote(t("全部节点"))}'
            f'{icon}'
        )
        manual_region_names.append(_quote(t(manual_name)))
    lines.append("")

    # ── 组合策略 ──
    auto_region_names = [_quote(t(rg.name)) for rg in auto_regions]
    all_region_names = auto_region_names + manual_region_names

    # 自动选择：包含所有自动地区组
    auto_select_members = auto_region_names + ([_quote(t("其他"))] if auto_regions else [])
    if auto_select_members:
        lines.append(
            f'{_quote(t("自动选择"))} = select, {", ".join(auto_select_members)}, '
            f'url=http://cp.cloudflare.com/generate_204, interval=300, tolerance=50, timeout=3, '
            f'icon-url=https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/05icon/lightning(5).png'
        )
    # 代理：自动选择 + 所有地区（自动+手动）
    proxy_members = []
    if auto_select_members:
        proxy_members.append(_quote(t("自动选择")))
    proxy_members.extend(all_region_names)
    if proxy_members:
        lines.append(
            f'{_quote(t("代理"))} = select, {", ".join(proxy_members)}, '
            f'icon-url=https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/05icon/rocket(1).png'
        )
    # 手动选择：大陆直连 + 自动选择 + 所有手动地区组
    manual_select_members = [_quote(t("大陆直连"))]
    if auto_select_members:
        manual_select_members.append(_quote(t("自动选择")))
    manual_select_members.extend(manual_region_names)
    if manual_region_names or auto_select_members:
        lines.append(
            f'{_quote(t("手动选择"))} = select, {", ".join(manual_select_members)}, '
            f'icon-url=https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/05icon/lightning.png'
        )
    lines.append("")

    # ── 服务分组 ──
    for sg in service_groups:
        pinned = [n for n in all_nodes if sg.name in (n.pinned_services or [])]
        pinned_names = [_display_name(n, sub_map) for n in pinned]
        policy_names = [t(p) for p in sg.policies]

        all_entries = pinned_names + policy_names
        entries_str = ", ".join(
            _quote(e) if " " in e else e for e in all_entries
        )
        icon = f', icon-url={sg.icon_url}' if sg.icon_url else ""
        lines.append(f'{_quote(t(sg.name))} = {sg.group_type}, {entries_str}{icon}')

    return lines


def _build_rules(rule_sources: list[RuleSource], pre_rules: list[CustomRule], general_rules: list[CustomRule], t, tc, tcomment) -> list[str]:
    lines = []

    # 前置自定义规则
    if pre_rules:
        lines.append(f"# >> {tcomment('pre_rules')}")
        for r in pre_rules:
            rule = r.rule_text
            parts = rule.split(",")
            if len(parts) >= 3:
                parts[-1] = t(parts[-1])
                lines.append(",".join(parts))
            else:
                lines.append(rule)
        lines.append("")

    # 规则集
    current_category = None
    for rs in rule_sources:
        if rs.category != current_category:
            current_category = rs.category
            lines.append(f"# >> {tc(current_category)}")

        translated_action = t(rs.action)
        lines.append(f"{rs.rule_type},{rs.url},{_quote(translated_action)}")

    # 通用自定义规则
    if general_rules:
        lines.append("")
        lines.append(f"# >> {tcomment('general_rules')}")
        for r in general_rules:
            rule = r.rule_text
            parts = rule.split(",")
            if len(parts) >= 3:
                parts[-1] = t(parts[-1])
                lines.append(",".join(parts))
            else:
                lines.append(rule)

    lines.append("")
    lines.append("RULE-SET,LAN,DIRECT")

    lines.append("")
    lines.append(f"# >> {tcomment('final_rule')}")
    lines.append(f"FINAL,{_quote(t('兜底'))},dns-failed")

    return lines
