"""默认数据种子 - 中文命名，arcangelw 控制器"""

# 完整的中英文名称映射表
# 数据库中统一存储中文名（左侧），生成英文配置时替换为右侧
LOCALE_NAMES = {
    # 虚拟组（generator 中硬编码的组名）
    "全部节点": "AllServer",
    "自动选择": "Automatic",
    "代理": "Proxy",
    "手动选择": "NoAuto",
    "其他": "Other",
    # 地区分组
    "香港": "Hong Kong",
    "台湾": "Taiwan",
    "日本": "Japan",
    "新加坡": "Singapore",
    "美国": "United States",
    "英国": "United Kingdom",
    "韩国": "Korea",
    # 服务分组
    "大陆直连": "Mainland",
    "AI服务": "AI",
    "Google服务": "Google",
    "苹果服务": "Apple",
    "微软服务": "Microsoft",
    "GitHub": "GitHub",
    "微信": "WeChat",
    "哔哩哔哩": "Bilibili",
    "测速": "Speedtest",
    "兜底": "Fallback",
    # 以下英文原名保持不变（无需映射）
    # "OneDrive", "Telegram", "X", "Netflix", "Disney+", "YouTube", "TikTok"
}


# 规则分类名翻译（数据库中 category 字段的英文名 → 中文）
CATEGORY_NAMES = {
    "unbreak": "规则修正",
    "adblock": "广告拦截",
    "mainland_app": "国内应用",
    "apple": "苹果服务",
    "ai": "AI 服务",
    "google": "谷歌服务",
    "streaming": "流媒体",
    "region_stream": "地区流媒体",
    "social": "社交媒体",
    "intl_service": "国际服务",
    "dev": "开发工具",
    "mainland": "国内规则",
    "global": "国外规则",
    "lan": "本地网络",
}

# 生成器中的固定注释翻译
COMMENT_NAMES = {
    "pre_rules": ("前置自定义规则", "Pre Custom Rules"),
    "general_rules": ("通用自定义规则", "General Custom Rules"),
    "lan": ("本地网络", "LAN"),
    "final_rule": ("兜底规则", "Final Rule"),
}


def locale_translate(name: str, locale: str = "zh") -> str:
    """将数据库中的中文名翻译为目标语言。zh 直接返回，en 查映射表。"""
    if locale == "zh" or not locale:
        return name
    # 手动地区组: "香港手动" -> "Hong Kong Manual"
    if name.endswith("手动"):
        region = name[:-2]
        en_region = LOCALE_NAMES.get(region, region)
        return f"{en_region} Manual"
    return LOCALE_NAMES.get(name, name)

DEFAULT_REGION_GROUPS = [
    {"name": "香港", "display_name": "香港 / Hong Kong", "filter_regex": "港|🇭🇰|香港|HK|Hong", "sort_order": 1,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/Hongkong.png",
     "auto_enabled": True, "manual_enabled": True},
    {"name": "台湾", "display_name": "台湾 / Taiwan", "filter_regex": "台|🇹🇼|台湾|TW|Tai", "sort_order": 2,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/taiwan.png",
     "auto_enabled": True, "manual_enabled": True},
    {"name": "日本", "display_name": "日本 / Japan", "filter_regex": "日|🇯🇵|日本|JP|Japan", "sort_order": 3,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/Japan(1).png",
     "auto_enabled": True, "manual_enabled": True},
    {"name": "新加坡", "display_name": "新加坡 / Singapore", "filter_regex": "坡|🇸🇬|新加坡|狮城|SG|Singapore", "sort_order": 4,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/singapore.png",
     "auto_enabled": True, "manual_enabled": True},
    {"name": "美国", "display_name": "美国 / United States", "filter_regex": "美|🇺🇸|美国|US|States|American", "sort_order": 5,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/US.png",
     "auto_enabled": True, "manual_enabled": True},
    {"name": "英国", "display_name": "英国 / United Kingdom", "filter_regex": "🇬🇧|英国|英|英格兰|UK|United Kingdom", "sort_order": 6,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/UnitedKingdom.png",
     "auto_enabled": False, "manual_enabled": False},
    {"name": "韩国", "display_name": "韩国 / Korea", "filter_regex": "韩|韩国|Korea|KR|🇰🇷", "sort_order": 7,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/Korea.png",
     "auto_enabled": False, "manual_enabled": False},
]

DEFAULT_SERVICE_GROUPS = [
    {"name": "大陆直连", "display_name": "大陆直连 / Mainland", "group_type": "select", "policies": ["DIRECT"], "sort_order": 0,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/05icon/direct.png"},
    {"name": "兜底", "display_name": "兜底 / Fallback", "group_type": "select",
     "policies": ["大陆直连", "自动选择", "美国", "美国手动", "日本", "日本手动", "新加坡", "新加坡手动"], "sort_order": 0,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/forward.png"},
    {"name": "AI服务", "display_name": "AI 服务 / AI Services", "group_type": "select",
     "policies": ["自动选择", "美国", "美国手动", "日本", "日本手动", "新加坡", "新加坡手动"], "sort_order": 1,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/chatgpt(1).png"},
    {"name": "Google服务", "display_name": "Google 服务 / Google", "group_type": "select",
     "policies": ["自动选择", "美国", "美国手动", "日本", "日本手动", "新加坡", "新加坡手动"], "sort_order": 2,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/google.png"},
    {"name": "苹果服务", "display_name": "苹果服务 / Apple", "group_type": "select",
     "policies": ["大陆直连", "香港", "美国", "美国手动"], "sort_order": 2,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/apple.png"},
    {"name": "微软服务", "display_name": "微软服务 / Microsoft", "group_type": "select",
     "policies": ["大陆直连", "香港", "新加坡", "美国", "美国手动"], "sort_order": 3,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/microsoft.png"},
    {"name": "OneDrive", "display_name": "OneDrive", "group_type": "select",
     "policies": ["大陆直连", "香港", "新加坡", "美国", "美国手动"], "sort_order": 4,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/OneDrive.png"},
    {"name": "GitHub", "display_name": "GitHub", "group_type": "select",
     "policies": ["自动选择", "美国", "美国手动", "日本", "日本手动", "新加坡", "新加坡手动", "香港", "香港手动"], "sort_order": 5,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/github.png"},
    {"name": "Telegram", "display_name": "Telegram", "group_type": "select",
     "policies": ["自动选择", "新加坡", "香港", "台湾", "日本", "美国", "美国手动"], "sort_order": 6,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/telegram.png"},
    {"name": "微信", "display_name": "微信 / WeChat", "group_type": "select",
     "policies": ["大陆直连", "香港", "新加坡", "美国", "美国手动"], "sort_order": 7,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/wechat.png"},
    {"name": "X", "display_name": "X / Twitter", "group_type": "select",
     "policies": ["自动选择", "香港", "香港手动", "台湾", "台湾手动", "新加坡", "新加坡手动", "日本", "日本手动", "美国", "美国手动"], "sort_order": 8,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/twitter.png"},
    {"name": "Netflix", "display_name": "Netflix", "group_type": "select",
     "policies": ["香港", "台湾", "新加坡", "日本", "美国", "美国手动"], "sort_order": 9,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/netflix.png"},
    {"name": "Disney+", "display_name": "Disney+", "group_type": "select",
     "policies": ["香港", "新加坡"], "sort_order": 10,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/disney.png"},
    {"name": "YouTube", "display_name": "YouTube", "group_type": "select",
     "policies": ["自动选择", "香港", "香港手动", "台湾", "台湾手动", "新加坡", "新加坡手动", "日本", "日本手动", "美国", "美国手动"], "sort_order": 11,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/Youtube.png"},
    {"name": "TikTok", "display_name": "TikTok", "group_type": "select",
     "policies": ["台湾", "新加坡", "日本", "美国", "美国手动"], "sort_order": 12,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/tiktok.png"},
    {"name": "哔哩哔哩", "display_name": "哔哩哔哩 / Bilibili", "group_type": "select",
     "policies": ["大陆直连", "香港", "台湾"], "sort_order": 13,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/bilibili.png"},
    {"name": "测速", "display_name": "测速 / Speedtest", "group_type": "select",
     "policies": ["大陆直连", "自动选择", "全部节点"], "sort_order": 14,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/speedtest.png"},
    {"name": "Global", "display_name": "Global", "group_type": "select",
     "policies": ["自动选择", "美国", "美国手动", "日本", "日本手动", "新加坡", "新加坡手动", "香港", "香港手动"], "sort_order": 15,
     "icon_url": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/05icon/rocket(1).png"},
]

# 规则源 - action 使用中文分组名（与上方保持一致）
DEFAULT_RULE_SOURCES = [
    # 规则修正
    {"name": "Unbreak", "url": "https://raw.githubusercontent.com/zxfccmm4/Profiles/refs/heads/main/Surge/Ruleset/Unbreak.list",
     "action": "DIRECT", "rule_type": "RULE-SET", "category": "unbreak", "sort_order": 0},
    # 广告拦截
    {"name": "Reject DomainSet", "url": "https://ruleset.skk.moe/List/domainset/reject.conf",
     "action": "REJECT", "rule_type": "DOMAIN-SET", "category": "adblock", "sort_order": 1},
    {"name": "Reject-Drop (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/reject-drop.conf",
     "action": "REJECT-DROP", "rule_type": "RULE-SET", "category": "adblock", "sort_order": 2},
    {"name": "Reject (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/reject.conf",
     "action": "REJECT", "rule_type": "RULE-SET", "category": "adblock", "sort_order": 3},
    {"name": "Reject (ip)", "url": "https://ruleset.skk.moe/List/ip/reject.conf",
     "action": "REJECT-DROP", "rule_type": "RULE-SET", "category": "adblock", "sort_order": 4},
    # 国内应用
    {"name": "WeChat", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/WeChat/WeChat.list",
     "action": "微信", "rule_type": "RULE-SET", "category": "mainland_app", "sort_order": 5},
    {"name": "NetEaseMusic (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/neteasemusic.conf",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland_app", "sort_order": 6},
    {"name": "NetEaseMusic (ip)", "url": "https://ruleset.skk.moe/List/ip/neteasemusic.conf",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland_app", "sort_order": 7},
    {"name": "Bilibili", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/BiliBili/BiliBili.list",
     "action": "哔哩哔哩", "rule_type": "RULE-SET", "category": "mainland_app", "sort_order": 8},
    {"name": "Weibo", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Weibo/Weibo.list",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland_app", "sort_order": 9},
    {"name": "XiaoHongShu", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/XiaoHongShu/XiaoHongShu.list",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland_app", "sort_order": 10},
    # Apple
    {"name": "AppStore", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AppStore/AppStore.list",
     "action": "DIRECT", "rule_type": "RULE-SET", "category": "apple", "sort_order": 11},
    {"name": "AppleNews", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AppleNews/AppleNews.list",
     "action": "美国", "rule_type": "RULE-SET", "category": "apple", "sort_order": 12},
    {"name": "Apple CDN", "url": "https://ruleset.skk.moe/List/domainset/apple_cdn.conf",
     "action": "苹果服务", "rule_type": "DOMAIN-SET", "category": "apple", "sort_order": 13},
    {"name": "AppleTV", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AppleTV/AppleTV.list",
     "action": "苹果服务", "rule_type": "RULE-SET", "category": "apple", "sort_order": 14},
    {"name": "Apple", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list",
     "action": "苹果服务", "rule_type": "RULE-SET", "category": "apple", "sort_order": 15},
    # 开发工具（提前，确保 GitHub 等走代理）
    {"name": "GitHub", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitHub/GitHub.list",
     "action": "GitHub", "rule_type": "RULE-SET", "category": "dev", "sort_order": 16},
    # AI
    {"name": "OpenAI", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list",
     "action": "AI服务", "rule_type": "RULE-SET", "category": "ai", "sort_order": 17},
    {"name": "Claude", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Claude/Claude.list",
     "action": "AI服务", "rule_type": "RULE-SET", "category": "ai", "sort_order": 18},
    {"name": "Gemini", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list",
     "action": "AI服务", "rule_type": "RULE-SET", "category": "ai", "sort_order": 19},
    {"name": "Bing", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Bing/Bing.list",
     "action": "AI服务", "rule_type": "RULE-SET", "category": "ai", "sort_order": 20},
    {"name": "AI 综合", "url": "https://ruleset.skk.moe/List/non_ip/ai.conf",
     "action": "AI服务", "rule_type": "RULE-SET", "category": "ai", "sort_order": 21},
    {"name": "AI 兜底", "url": "https://raw.githubusercontent.com/EAlyce/conf/refs/heads/main/Rule/OpenAI.list",
     "action": "AI服务", "rule_type": "RULE-SET", "category": "ai", "sort_order": 22},
    # Google
    {"name": "Google", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list",
     "action": "Google服务", "rule_type": "RULE-SET", "category": "google", "sort_order": 23},
    # 流媒体
    {"name": "Disney+", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Disney/Disney.list",
     "action": "Disney+", "rule_type": "RULE-SET", "category": "streaming", "sort_order": 24},
    {"name": "Netflix", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Netflix/Netflix.list",
     "action": "Netflix", "rule_type": "RULE-SET", "category": "streaming", "sort_order": 25},
    {"name": "TikTok", "url": "https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Surge/TikTok.list",
     "action": "TikTok", "rule_type": "RULE-SET", "category": "streaming", "sort_order": 26},
    {"name": "YouTube", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list",
     "action": "YouTube", "rule_type": "RULE-SET", "category": "streaming", "sort_order": 27},
    {"name": "Emby", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Emby/Emby.list",
     "action": "Global", "rule_type": "RULE-SET", "category": "streaming", "sort_order": 28},
    # 地区流媒体
    {"name": "Stream US (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/stream_us.conf",
     "action": "美国", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 29},
    {"name": "Stream US (ip)", "url": "https://ruleset.skk.moe/List/ip/stream_us.conf",
     "action": "美国", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 30},
    {"name": "Stream EU (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/stream_eu.conf",
     "action": "英国", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 31},
    {"name": "Stream EU (ip)", "url": "https://ruleset.skk.moe/List/ip/stream_eu.conf",
     "action": "英国", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 32},
    {"name": "Stream JP (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/stream_jp.conf",
     "action": "日本", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 33},
    {"name": "Stream JP (ip)", "url": "https://ruleset.skk.moe/List/ip/stream_jp.conf",
     "action": "日本", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 34},
    {"name": "Stream KR (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/stream_kr.conf",
     "action": "韩国", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 35},
    {"name": "Stream KR (ip)", "url": "https://ruleset.skk.moe/List/ip/stream_kr.conf",
     "action": "韩国", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 36},
    {"name": "Stream HK (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/stream_hk.conf",
     "action": "香港", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 37},
    {"name": "Stream HK (ip)", "url": "https://ruleset.skk.moe/List/ip/stream_hk.conf",
     "action": "香港", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 38},
    {"name": "Stream TW (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/stream_tw.conf",
     "action": "台湾", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 39},
    {"name": "Stream TW (ip)", "url": "https://ruleset.skk.moe/List/ip/stream_tw.conf",
     "action": "台湾", "rule_type": "RULE-SET", "category": "region_stream", "sort_order": 40},
    # 社交媒体
    {"name": "Twitter", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list",
     "action": "X", "rule_type": "RULE-SET", "category": "social", "sort_order": 41},
    {"name": "Telegram (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/telegram.conf",
     "action": "Telegram", "rule_type": "RULE-SET", "category": "social", "sort_order": 42},
    {"name": "Telegram (ip)", "url": "https://ruleset.skk.moe/List/ip/telegram.conf",
     "action": "Telegram", "rule_type": "RULE-SET", "category": "social", "sort_order": 43},
    {"name": "Telegram ASN", "url": "https://ruleset.skk.moe/List/ip/telegram_asn.conf",
     "action": "Telegram", "rule_type": "RULE-SET", "category": "social", "sort_order": 44},
    {"name": "Facebook", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Facebook/Facebook.list",
     "action": "Global", "rule_type": "RULE-SET", "category": "social", "sort_order": 45},
    {"name": "Instagram", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Instagram/Instagram.list",
     "action": "Global", "rule_type": "RULE-SET", "category": "social", "sort_order": 46},
    {"name": "Threads", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Threads/Threads.list",
     "action": "Global", "rule_type": "RULE-SET", "category": "social", "sort_order": 47},
    {"name": "Discord", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Discord/Discord.list",
     "action": "Global", "rule_type": "RULE-SET", "category": "social", "sort_order": 48},
    # 其他国外服务
    {"name": "OneDrive", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OneDrive/OneDrive.list",
     "action": "OneDrive", "rule_type": "RULE-SET", "category": "intl_service", "sort_order": 49},
    {"name": "Microsoft", "url": "https://ruleset.skk.moe/List/non_ip/microsoft.conf",
     "action": "微软服务", "rule_type": "RULE-SET", "category": "intl_service", "sort_order": 50},
    {"name": "Speedtest", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Speedtest/Speedtest.list",
     "action": "测速", "rule_type": "RULE-SET", "category": "intl_service", "sort_order": 51},
    {"name": "Riot", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Riot/Riot.list",
     "action": "美国", "rule_type": "RULE-SET", "category": "intl_service", "sort_order": 52},
    # 国内规则
    {"name": "Direct", "url": "https://ruleset.skk.moe/List/non_ip/direct.conf",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland", "sort_order": 53},
    {"name": "Domestic (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/domestic.conf",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland", "sort_order": 54},
    {"name": "Domestic (ip)", "url": "https://ruleset.skk.moe/List/ip/domestic.conf",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland", "sort_order": 55},
    {"name": "ChinaMax", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMax/ChinaMax.list",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland", "sort_order": 56},
    {"name": "ASN China", "url": "https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.China.list",
     "action": "DIRECT", "rule_type": "RULE-SET", "category": "mainland", "sort_order": 57},
    {"name": "Download (domainset)", "url": "https://ruleset.skk.moe/List/domainset/download.conf",
     "action": "大陆直连", "rule_type": "DOMAIN-SET", "category": "mainland", "sort_order": 58},
    {"name": "Download (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/download.conf",
     "action": "大陆直连", "rule_type": "RULE-SET", "category": "mainland", "sort_order": 59},
    # 国外规则
    {"name": "CDN (domainset)", "url": "https://ruleset.skk.moe/List/domainset/cdn.conf",
     "action": "Global", "rule_type": "DOMAIN-SET", "category": "global", "sort_order": 60},
    {"name": "CDN (non_ip)", "url": "https://ruleset.skk.moe/List/non_ip/cdn.conf",
     "action": "Global", "rule_type": "RULE-SET", "category": "global", "sort_order": 61},
    {"name": "Global Plus", "url": "https://ruleset.skk.moe/List/non_ip/global_plus.conf",
     "action": "Global", "rule_type": "RULE-SET", "category": "global", "sort_order": 62},
    {"name": "Global", "url": "https://ruleset.skk.moe/List/non_ip/global.conf",
     "action": "Global", "rule_type": "RULE-SET", "category": "global", "sort_order": 63},
    # 本地网络
    {"name": "LAN", "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list",
     "action": "DIRECT", "rule_type": "RULE-SET", "category": "lan", "sort_order": 64},
]

# 控制器默认使用 arcangelw
DEFAULT_GENERAL = {
    "wifi-assist": True,
    "all-hybrid": False,
    "udp-priority": False,
    "internet-test-url": "http://connectivitycheck.gstatic.com/generate_204",
    "proxy-test-url": "http://captive.apple.com/generate_204",
    "test-timeout": 3,
    "geoip-maxmind-url": "https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb",
    "ipv6": False,
    "ipv6-vif": "auto",
    "allow-wifi-access": False,
    "wifi-access-http-port": 6152,
    "wifi-access-socks5-port": 6153,
    "http-listen": "0.0.0.0",
    "socks5-listen": "0.0.0.0",
    "allow-hotspot-access": True,
    "external-controller-access": "arcangelw@0.0.0.0:6160",
    "http-api": "arcangelw@0.0.0.0:6166",
    "http-api-tls": True,
    "http-api-web-dashboard": True,
    "compatibility-mode": 1,
    "skip-proxy": "localhost, *.local, captive.apple.com, guzzoni.apple.com, 0.0.0.0/8, 10.0.0.0/8, 17.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 192.88.99.0/24, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 240.0.0.0/4, 255.255.255.255/32",
    "exclude-simple-hostnames": True,
    "read-etc-hosts": True,
    "use-local-host-item-for-proxy": True,
    "encrypted-dns-follow-outbound-mode": False,
    "include-all-networks": False,
    "include-local-networks": False,
    "dns-server": "223.5.5.5, 223.6.6.6, 119.29.29.29",
    "encrypted-dns-server": "https://doh.pub/dns-query, https://dns.alidns.com/dns-query",
    "loglevel": "notify",
    "show-error-page-for-reject": True,
    "always-real-ip": "link-ip.nextdns.io, *.msftconnecttest.com, *.msftncsi.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.logon.battlenet.com.cn, *.logon.battle.net, stun.l.google.com",
    "hijack-dns": "8.8.8.8:53, 8.8.4.4:53",
    "udp-policy-not-supported-behaviour": "REJECT",
    "proxy-restricted-to-lan": False,
}

DEFAULT_HOST_MAPPINGS = [
    # 阿里 DNS (223.5.5.5)
    {"domain": "*.taobao.com", "target": "server:223.5.5.5", "sort_order": 0},
    {"domain": "*.tmall.com", "target": "server:223.5.5.5", "sort_order": 1},
    {"domain": "*.alipay.com", "target": "server:223.5.5.5", "sort_order": 2},
    {"domain": "*.alicdn.com", "target": "server:223.5.5.5", "sort_order": 3},
    {"domain": "*.aliyun.com", "target": "server:223.5.5.5", "sort_order": 4},
    # 腾讯 DNS (119.28.28.28)
    {"domain": "*.jd.com", "target": "server:119.28.28.28", "sort_order": 10},
    {"domain": "*.qq.com", "target": "server:119.28.28.28", "sort_order": 11},
    {"domain": "*.tencent.com", "target": "server:119.28.28.28", "sort_order": 12},
    {"domain": "*.weixin.com", "target": "server:119.28.28.28", "sort_order": 13},
    # 腾讯 DNSPod (119.29.29.29)
    {"domain": "*.bilibili.com", "target": "server:119.29.29.29", "sort_order": 20},
    {"domain": "hdslb.com", "target": "server:119.29.29.29", "sort_order": 21},
    {"domain": "*.163.com", "target": "server:119.29.29.29", "sort_order": 22},
    {"domain": "*.126.com", "target": "server:119.29.29.29", "sort_order": 23},
    {"domain": "*.126.net", "target": "server:119.29.29.29", "sort_order": 24},
    {"domain": "*.127.net", "target": "server:119.29.29.29", "sort_order": 25},
    {"domain": "*.netease.com", "target": "server:119.29.29.29", "sort_order": 26},
    {"domain": "*.mi.com", "target": "server:119.29.29.29", "sort_order": 27},
    {"domain": "*.xiaomi.com", "target": "server:119.29.29.29", "sort_order": 28},
    {"domain": "dl.google.com", "target": "server:119.29.29.29", "sort_order": 29},
    {"domain": "dl.l.google.com", "target": "server:119.29.29.29", "sort_order": 30},
    {"domain": "update.googleapis.com", "target": "server:119.29.29.29", "sort_order": 31},
    # Google DNS (8.8.4.4)
    {"domain": "*testflight.apple.com", "target": "server:8.8.4.4", "sort_order": 40},
    # 直连 IP
    {"domain": "mtalk.google.com", "target": "108.177.125.188", "sort_order": 50},
    # 路由器管理页面 → 系统默认 DNS
    {"domain": "amplifi.lan", "target": "server:system", "sort_order": 60},
    {"domain": "router.synology.com", "target": "server:system", "sort_order": 61},
    {"domain": "sila.razer.com", "target": "server:system", "sort_order": 62},
    {"domain": "router.asus.com", "target": "server:system", "sort_order": 63},
    {"domain": "routerlogin.net", "target": "server:system", "sort_order": 64},
    {"domain": "orbilogin.com", "target": "server:system", "sort_order": 65},
    {"domain": "www.LinksysSmartWiFi.com", "target": "server:system", "sort_order": 66},
    {"domain": "LinksysSmartWiFi.com", "target": "server:system", "sort_order": 67},
    {"domain": "myrouter.local", "target": "server:system", "sort_order": 68},
    {"domain": "www.miwifi.com", "target": "server:system", "sort_order": 69},
    {"domain": "miwifi.com", "target": "server:system", "sort_order": 70},
    {"domain": "mediarouter.home", "target": "server:system", "sort_order": 71},
    {"domain": "tplogin.cn", "target": "server:system", "sort_order": 72},
    {"domain": "tplinklogin.net", "target": "server:system", "sort_order": 73},
    {"domain": "melogin.cn", "target": "server:system", "sort_order": 74},
    {"domain": "falogin.cn", "target": "server:system", "sort_order": 75},
]

# Host 映射预置 DNS 选项
HOST_DNS_PRESETS = [
    {"value": "server:system", "label_zh": "系统默认 DNS", "label_en": "System DNS"},
    {"value": "server:223.5.5.5", "label_zh": "阿里 DNS (223.5.5.5)", "label_en": "AliDNS (223.5.5.5)"},
    {"value": "server:119.29.29.29", "label_zh": "腾讯 DNSPod (119.29.29.29)", "label_en": "DNSPod (119.29.29.29)"},
    {"value": "server:119.28.28.28", "label_zh": "腾讯 DNS (119.28.28.28)", "label_en": "Tencent DNS (119.28.28.28)"},
    {"value": "server:8.8.4.4", "label_zh": "Google DNS (8.8.4.4)", "label_en": "Google DNS (8.8.4.4)"},
    {"value": "server:8.8.8.8", "label_zh": "Google DNS (8.8.8.8)", "label_en": "Google DNS (8.8.8.8)"},
    {"value": "server:1.1.1.1", "label_zh": "Cloudflare DNS (1.1.1.1)", "label_en": "Cloudflare DNS (1.1.1.1)"},
]

DEFAULT_URL_REWRITES = [
    "^https?:\\/\\/(www\\.)?(g|google)\\.cn https://www.google.com 302",
    "^https?:\\/\\/(ditu|maps)\\.google\\.cn https://maps.google.com 302",
    "^https?:\\/\\/(www\\.)?taobao\\.com\\/ https://taobao.com/ 302",
    "^https?:\\/\\/(www\\.)?jd\\.com\\/ https://www.jd.com/ 302",
    "^https?:\\/\\/(www\\.)?mi\\.com\\/ https://www.mi.com/ 302",
    "^https?:\\/\\/(www\\.)?suning\\.com\\/ https://suning.com/ 302",
    "^https?:\\/\\/(www\\.)?yhd\\.com\\/ https://yhd.com/ 302",
    "^https?:\\/\\/api\\.abema\\.io\\/v\\d\\/ip\\/check - reject",
]

DEFAULT_HEADER_REWRITES = [
    "http-request ^https:\\/\\/github\\.com\\/ header-replace Accept-Language en-us",
    "http-request ^https:\\/\\/(raw|gist)\\.githubusercontent\\.com\\/ header-replace Accept-Language en-us",
]

DEFAULT_MITM = {
    "skip-server-cert-verify": True,
    "tcp-connection": True,
    "h2": True,
    "hostname": "www.google.cn, api.abema.io, *.zhihu.com, -CUSTOMMitM, sub.store",
}

# 前置自定义规则 - 放在规则集之前，覆盖规则集的匹配
DEFAULT_PRE_RULES = [
    {"rule_text": "DOMAIN,app-site-association.cdn-apple.com,REJECT", "position": "pre", "sort_order": 0,
     "comment": "拦截 Apple AASA 文件"},
    {"rule_text": "DOMAIN,prpr.96110.cn.com,DIRECT", "position": "pre", "sort_order": 1,
     "comment": "反诈直连"},
    {"rule_text": "DOMAIN-KEYWORD,96110,REJECT", "position": "pre", "sort_order": 2,
     "comment": "拦截反诈域名"},
    {"rule_text": "DOMAIN-SUFFIX,gjfzpt.cn,REJECT", "position": "pre", "sort_order": 3,
     "comment": "拦截反诈域名"},
    {"rule_text": "DOMAIN-SUFFIX,apple-relay.apple.com,AI服务", "position": "pre", "sort_order": 4,
     "comment": "Apple Relay → AI（覆盖 Apple 规则集）"},
    {"rule_text": "DOMAIN-SUFFIX,apple-relay.cloudflare.com,AI服务", "position": "pre", "sort_order": 5,
     "comment": "Apple Relay Cloudflare → AI"},
    {"rule_text": "DOMAIN-KEYWORD,apple-relay,AI服务", "position": "pre", "sort_order": 6,
     "comment": "Apple Relay 关键字 → AI"},
    {"rule_text": "DOMAIN-SUFFIX,googleapis.com,AI服务", "position": "pre", "sort_order": 7,
     "comment": "Google APIs → AI（覆盖 Google 规则集）"},
    {"rule_text": "DOMAIN-KEYWORD,diabrowser.engineering,AI服务", "position": "pre", "sort_order": 8,
     "comment": "AI 浏览器 → AI 服务"},
    {"rule_text": "DOMAIN-SUFFIX,diabrowser.engineering,AI服务", "position": "pre", "sort_order": 9,
     "comment": "AI 浏览器域名 → AI 服务"},
    {"rule_text": "AND,((PROTOCOL,UDP), (DOMAIN-SUFFIX,googlevideo.com)),REJECT-NO-DROP", "position": "pre", "sort_order": 10,
     "comment": "拦截 YouTube UDP 流量"},
    {"rule_text": "DOMAIN-SUFFIX,z.ai,大陆直连", "position": "pre", "sort_order": 11,
     "comment": "智谱AI"},
]

# 通用自定义规则 - 放在规则集之后，补充未覆盖的域名
DEFAULT_GENERAL_RULES = [
    {"rule_text": "DOMAIN-SUFFIX,vercel.app,Global", "position": "general", "sort_order": 0,
     "comment": "Vercel 托管服务"},
    {"rule_text": "DOMAIN-SUFFIX,mypikpak.com,美国", "position": "general", "sort_order": 1,
     "comment": "PikPak 网盘"},
    {"rule_text": "DOMAIN-SUFFIX,nssurge.com,Global", "position": "general", "sort_order": 2,
     "comment": "Surge 官网"},
    {"rule_text": "DOMAIN-SUFFIX,surgee.me,Global", "position": "general", "sort_order": 3,
     "comment": "Surge 社区"},
    {"rule_text": "DOMAIN-SUFFIX,www.torrentmac.net,Global", "position": "general", "sort_order": 4,
     "comment": "Mac 软件下载"},
    {"rule_text": "DOMAIN-SUFFIX,cloudflare.com,Global", "position": "general", "sort_order": 5,
     "comment": "Cloudflare CDN"},
    {"rule_text": "DOMAIN,jable.tv,Global", "position": "general", "sort_order": 6,
     "comment": "流媒体"},
    {"rule_text": "DOMAIN,api.amplitude.com,Global", "position": "general", "sort_order": 7,
     "comment": "数据分析平台"},
    {"rule_text": "DOMAIN,m.cmx.im,Global", "position": "general", "sort_order": 8,
     "comment": "RSS 服务"},
    {"rule_text": "DOMAIN-SUFFIX,api.themoviedb.org,Global", "position": "general", "sort_order": 9,
     "comment": "TMDB 电影数据库"},
    {"rule_text": "DOMAIN-SUFFIX,appstorrent.ru,DIRECT", "position": "general", "sort_order": 10,
     "comment": "Mac 软件下载（直连）"},
    {"rule_text": "DOMAIN-SUFFIX,smtp,DIRECT", "position": "general", "sort_order": 11,
     "comment": "邮件协议直连"},
    {"rule_text": "URL-REGEX,(Subject|HELO|SMTP),DIRECT", "position": "general", "sort_order": 12,
     "comment": "邮件协议直连"},
]
